name: Auto Publish

# Controls when the workflow will run
on:
  # The triggers of workflow
  push:
    # Where should trigger it. In our case, only on master branch.
    tag:
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-gpr:
    name: 'BUILD & PUBLISH the Package'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@brandalley'

      - name: INSTALL - Install package.json dependencies with Yarn
        run: npm install

      - name: FORMAT - Format the code to follow the prettier patterns
        run: npm run format

      - name: PREBUILD - Clear the dist folder and auto import all the modules
        run: npm run prebuild

      - name: BUILD - Build the bandle using tsc and rollup
        run: npm run build

      - name: TEST - Lint, test and depcheck
        run: npm run test:prod

      - name: PUBLISH - Publish the packages to npm using GitHub Packages
        run: npm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}" && npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
