name: Publish the Package

# Controls when the workflow will run
on:
  # The triggers of workflow
  push:
    # Where should trigger it. In our case, only on master branch.
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Publish to GitHub Package Repository
  publish-gpr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@brandalley'

      - name: INSTALL - Install package.json dependencies with Yarn
        run: npm install

      - name: FORMAT - Format the code to follow the prettier patterns
        run: npm run format

      - name: PREBUILD - Clear the dist folder and auto import all the modules
        run: npm run prebuild

      - name: BUILD - Build the bandle using tsc and rollup
        run: npm run build

      - name: TEST - Lint, test and depcheck
        run: npm run test:prod

      - name: PUBLISH - Publish the packages to npm using GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
