name: Validate PR Description

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, edited, synchronize]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-description:
    name: Check that PR has description
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is shame-worthy
        id: is-shame-worthy
        run: |
          FILTERED_BODY=$( sed -r -e '/^(##? )|(- *\[)/d' <<< $RAW_BODY )
          echo "::debug::Filtered PR body to $FILTERED_BODY"
          if [[ -z "${FILTERED_BODY//[[:space:]]/}" ]]; then
              echo "::set-output name=is-shame-worthy::true"
          else
              echo "::set-output name=is-shame-worthy::false"
          fi
        env:
          RAW_BODY: ${{ github.event.pull_request.body }}

      - name: Shame if PR has no description
        if: steps.is-shame-worthy.outputs.is-shame-worthy == 'true'
        run: |
          SHAME_BODY="Hey @${{ github.actor }}! 👋\nThis PR seems to contain no description. Please add useful context, test instructions and/or any other information that will help the reviewers to test, review and approve it."
          curl -s -u posthog-bot:${{ secrets.GITHUB_TOKEN }} -X POST -d "{ \"body\": \"$SHAME_BODY\" }" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

      - uses: actions/checkout@v1

      - name: Fail checks if PR has no description
        if: steps.is-shame-worthy.outputs.is-shame-worthy == 'true'
        run: exit 1
